spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: "file:///home/kyialbek/Documents/spring-cloud/config/"
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/Kyialbek-Temirbekov/spring-cloud-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071

logging:
  pattern:
    level: "%5p[${spring.application.name},%X{trace.id},%X{span.id}]"